"""fenced provider jobs and replay audit

Revision ID: 6e9edd6daa17
Revises: 7b26efb1d423
Create Date: 2026-09-10 00:42:05.299008

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6e9edd6daa17"
down_revision: Union[str, Sequence[str], None] = "7b26efb1d423"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("outbox", sa.Column("finished_at", sa.String(length=40), nullable=True))
    op.create_table(
        "job_replays",
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("new_job_id", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("source_id"),
        sa.UniqueConstraint("new_job_id"),
    )
    op.create_index("ix_outbox_ready", "outbox", ["state", "due_at", "created_at"], unique=False)
    op.add_column(
        "provider_states", sa.Column("consecutive_failures", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column("provider_states", sa.Column("next_attempt_at", sa.String(length=40), nullable=True))
    op.add_column("provider_states", sa.Column("last_attempt_at", sa.String(length=40), nullable=True))
    op.add_column("provider_states", sa.Column("lease_job_id", sa.String(length=64), nullable=True))
    op.add_column("provider_states", sa.Column("lease_attempt", sa.Integer(), nullable=True))
    op.add_column("provider_states", sa.Column("lease_until", sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("provider_states", "lease_until")
    op.drop_column("provider_states", "lease_attempt")
    op.drop_column("provider_states", "lease_job_id")
    op.drop_column("provider_states", "last_attempt_at")
    op.drop_column("provider_states", "next_attempt_at")
    op.drop_column("provider_states", "consecutive_failures")
    op.drop_index("ix_outbox_ready", table_name="outbox")
    op.drop_table("job_replays")
    op.drop_column("outbox", "finished_at")
    # ### end Alembic commands ###
