"""client authorization and command receipts

Revision ID: 721f5dc7b8c2
Revises: b5e150717423
Create Date: 2026-09-09 22:59:20.580022

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "721f5dc7b8c2"
down_revision: Union[str, Sequence[str], None] = "b5e150717423"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "command_receipts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("owner_id", sa.String(length=128), nullable=False),
        sa.Column("operation", sa.String(length=80), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("expires_at", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_command_receipts_expires_at"), "command_receipts", ["expires_at"], unique=False)
    op.create_index(op.f("ix_command_receipts_owner_id"), "command_receipts", ["owner_id"], unique=False)
    op.create_table(
        "oauth_clients",
        sa.Column("id", sa.String(length=200), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("metadata_ciphertext", sa.Text(), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "oauth_grants",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("owner_id", sa.String(length=128), nullable=False),
        sa.Column("client_id", sa.String(length=200), nullable=False),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.Column("resource", sa.String(length=500), nullable=False),
        sa.Column("issuer", sa.String(length=500), nullable=False),
        sa.Column("expires_at", sa.BigInteger(), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_oauth_grants_owner_id"), "oauth_grants", ["owner_id"], unique=False)
    op.create_table(
        "oauth_requests",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("client_id", sa.String(length=200), nullable=False),
        sa.Column("owner_id", sa.String(length=128), nullable=True),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("expires_at", sa.BigInteger(), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.Column("consumed", sa.Boolean(), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=True),
        sa.Column("code_expires_at", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code_hash"),
    )
    op.create_index(op.f("ix_oauth_requests_client_id"), "oauth_requests", ["client_id"], unique=False)
    op.create_table(
        "oauth_tokens",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("grant_id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.Column("expires_at", sa.BigInteger(), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    op.create_index(op.f("ix_oauth_tokens_grant_id"), "oauth_tokens", ["grant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_oauth_tokens_grant_id"), table_name="oauth_tokens")
    op.drop_table("oauth_tokens")
    op.drop_index(op.f("ix_oauth_requests_client_id"), table_name="oauth_requests")
    op.drop_table("oauth_requests")
    op.drop_index(op.f("ix_oauth_grants_owner_id"), table_name="oauth_grants")
    op.drop_table("oauth_grants")
    op.drop_table("oauth_clients")
    op.drop_index(op.f("ix_command_receipts_owner_id"), table_name="command_receipts")
    op.drop_index(op.f("ix_command_receipts_expires_at"), table_name="command_receipts")
    op.drop_table("command_receipts")
    # ### end Alembic commands ###
