"""reviewed broadcast records and audit trail

Revision ID: 7b26efb1d423
Revises: 721f5dc7b8c2
Create Date: 2026-09-10 00:03:23.007328

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7b26efb1d423"
down_revision: Union[str, Sequence[str], None] = "721f5dc7b8c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "broadcast_audit",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("link_id", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_broadcast_audit_link_id"), "broadcast_audit", ["link_id"], unique=False)
    op.create_table(
        "broadcast_records",
        sa.Column("link_id", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("draft", sa.JSON(), nullable=False),
        sa.Column("published", sa.JSON(), nullable=True),
        sa.Column("published_revision", sa.Integer(), nullable=True),
        sa.Column("device_tests", sa.JSON(), nullable=False),
        sa.Column("network_status", sa.String(length=40), nullable=False),
        sa.Column("network_checked_at", sa.String(length=40), nullable=True),
        sa.Column("next_check_at", sa.String(length=40), nullable=False),
        sa.Column("missing_count", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("link_id"),
    )
    op.create_index(
        op.f("ix_broadcast_records_next_check_at"), "broadcast_records", ["next_check_at"], unique=False
    )
    op.create_index(op.f("ix_broadcast_records_status"), "broadcast_records", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_broadcast_records_status"), table_name="broadcast_records")
    op.drop_index(op.f("ix_broadcast_records_next_check_at"), table_name="broadcast_records")
    op.drop_table("broadcast_records")
    op.drop_index(op.f("ix_broadcast_audit_link_id"), table_name="broadcast_audit")
    op.drop_table("broadcast_audit")
    # ### end Alembic commands ###
