"""shared video discovery and personal reviews

Revision ID: b5e150717423
Revises: d1a62b28b046
Create Date: 2026-09-09 22:16:56.450830

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b5e150717423"
down_revision: Union[str, Sequence[str], None] = "d1a62b28b046"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channel_sync",
        sa.Column("channel_id", sa.String(length=80), nullable=False),
        sa.Column("last_success", sa.String(length=40), nullable=True),
        sa.Column("next_poll_at", sa.String(length=40), nullable=False),
        sa.Column("callback_id", sa.String(length=64), nullable=False),
        sa.Column("secret_ciphertext", sa.Text(), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("pending_until", sa.String(length=40), nullable=True),
        sa.Column("lease_expires_at", sa.String(length=40), nullable=True),
        sa.Column("renew_at", sa.String(length=40), nullable=True),
        sa.Column("last_notification_at", sa.String(length=40), nullable=True),
        sa.Column("error", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("channel_id"),
        sa.UniqueConstraint("callback_id"),
    )
    op.create_table(
        "notification_receipts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("channel_id", sa.String(length=80), nullable=False),
        sa.Column("received_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_receipts_channel_id"), "notification_receipts", ["channel_id"], unique=False
    )
    op.create_table(
        "video_matches",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("owner_id", sa.String(length=128), nullable=False),
        sa.Column("video_id", sa.String(length=40), nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("decision", sa.String(length=24), nullable=False),
        sa.Column("reason_codes", sa.JSON(), nullable=False),
        sa.Column("rule_version", sa.String(length=40), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "video_id", "event_id"),
    )
    op.create_index(op.f("ix_video_matches_event_id"), "video_matches", ["event_id"], unique=False)
    op.create_index(op.f("ix_video_matches_owner_id"), "video_matches", ["owner_id"], unique=False)
    op.create_index(op.f("ix_video_matches_video_id"), "video_matches", ["video_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_video_matches_video_id"), table_name="video_matches")
    op.drop_index(op.f("ix_video_matches_owner_id"), table_name="video_matches")
    op.drop_index(op.f("ix_video_matches_event_id"), table_name="video_matches")
    op.drop_table("video_matches")
    op.drop_index(op.f("ix_notification_receipts_channel_id"), table_name="notification_receipts")
    op.drop_table("notification_receipts")
    op.drop_table("channel_sync")
    # ### end Alembic commands ###
