"""Initial calendar domain

Revision ID: d1a62b28b046
Revises:
Create Date: 2026-09-09 21:45:12.645037

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "d1a62b28b046"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "creators",
        sa.Column("channel_id", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("uploads_id", sa.String(length=100), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.Column("last_error", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("channel_id"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("source_key", sa.String(length=220), nullable=False),
        sa.Column("competition_id", sa.String(length=160), nullable=False),
        sa.Column("sport", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("starts_at", sa.String(length=40), nullable=True),
        sa.Column("local_date", sa.String(length=10), nullable=True),
        sa.Column("time_precision", sa.String(length=16), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("venue", sa.String(length=240), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("participants", sa.JSON(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.Column("demo", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_key"),
    )
    op.create_index(op.f("ix_events_competition_id"), "events", ["competition_id"], unique=False)
    op.create_index(op.f("ix_events_starts_at"), "events", ["starts_at"], unique=False)
    op.create_table(
        "feeds",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("owner_id", sa.String(length=128), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("token_ciphertext", sa.Text(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("paused", sa.Boolean(), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("body", sa.Text().with_variant(mysql.LONGTEXT(), "mysql"), nullable=False),
        sa.Column("etag", sa.String(length=64), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "links",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("owner_id", sa.String(length=128), nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("url_hash", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("platform", sa.String(length=100), nullable=False),
        sa.Column("channel_id", sa.String(length=80), nullable=False),
        sa.Column("creator", sa.String(length=140), nullable=False),
        sa.Column("origin", sa.String(length=24), nullable=False),
        sa.Column("access", sa.String(length=30), nullable=False),
        sa.Column("regions", sa.JSON(), nullable=False),
        sa.Column("available", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "event_id", "url_hash"),
    )
    op.create_index(op.f("ix_links_event_id"), "links", ["event_id"], unique=False)
    op.create_index(op.f("ix_links_owner_id"), "links", ["owner_id"], unique=False)
    op.create_table(
        "outbox",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("due_at", sa.String(length=40), nullable=False),
        sa.Column("error", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_outbox_kind"), "outbox", ["kind"], unique=False)
    op.create_index(op.f("ix_outbox_state"), "outbox", ["state"], unique=False)
    op.create_table(
        "projections",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("feed_id", sa.String(length=64), nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.Column("removed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("feed_id", "event_id"),
    )
    op.create_index(op.f("ix_projections_feed_id"), "projections", ["feed_id"], unique=False)
    op.create_table(
        "provider_states",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("last_success", sa.String(length=40), nullable=True),
        sa.Column("error", sa.String(length=100), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "sources",
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("short_name", sa.String(length=40), nullable=False),
        sa.Column("sport", sa.String(length=30), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("color", sa.String(length=10), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("demo", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "videos",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("channel_id", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("published_at", sa.String(length=40), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.Column("available", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_videos_channel_id"), "videos", ["channel_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_videos_channel_id"), table_name="videos")
    op.drop_table("videos")
    op.drop_table("users")
    op.drop_table("sources")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("provider_states")
    op.drop_index(op.f("ix_projections_feed_id"), table_name="projections")
    op.drop_table("projections")
    op.drop_index(op.f("ix_outbox_state"), table_name="outbox")
    op.drop_index(op.f("ix_outbox_kind"), table_name="outbox")
    op.drop_table("outbox")
    op.drop_index(op.f("ix_links_owner_id"), table_name="links")
    op.drop_index(op.f("ix_links_event_id"), table_name="links")
    op.drop_table("links")
    op.drop_table("feeds")
    op.drop_index(op.f("ix_events_starts_at"), table_name="events")
    op.drop_index(op.f("ix_events_competition_id"), table_name="events")
    op.drop_table("events")
    op.drop_table("creators")
    # ### end Alembic commands ###
